# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

# ignoring warning from pods
inhibit_all_warnings!

target "PhotoBrowserDemo" do

pod 'AFNetworking', '~> 2.2.4'
pod 'DACircularProgress', '~> 2.2'

pod 'DCIntrospect-ARC'

end
